export enum OrderStatus {
  DRAFT = 'DRAFT',
  PAYMENT_PROCESSING = 'PAYMENT-PROCESSING',
  AWAITING_DEPOSIT = 'AWAITING-DEPOSIT',
  ORDER_PROCESSING = 'ORDER-PROCESSING',
  COMPLETED = 'COMPLETED',
  CONFIRMED = 'CONFIRMED',
  CS_PROCESSING = 'CS-PROCESSING',
  EXPIRED = 'EXPIRED',
}
